const ADMIN_API_URL="/adminApi"

const LOGIN_ADMIN_URL=  ADMIN_API_URL+"/LoginAdmin"
const ADMIN_CREATE_ACCOUNT_URL=    ADMIN_API_URL+"/CreateAdmin"
const ADMIN_CHANGE_PASS_URL=    ADMIN_API_URL+"/AdminChangePass"
const ADMIN_RESET_PASS_URL=   ADMIN_API_URL+"/AdminResetPass"
const LOGOUT_ADMIN_URL=    ADMIN_API_URL+"/LogoutAdmin"
const VIEW_ADMIN_PROFILE_URL=    ADMIN_API_URL+"/viewAdminProfile"

export {
    LOGIN_ADMIN_URL,
ADMIN_CHANGE_PASS_URL,
ADMIN_CREATE_ACCOUNT_URL,
ADMIN_RESET_PASS_URL,
LOGOUT_ADMIN_URL,
VIEW_ADMIN_PROFILE_URL}