LOGIN_ADMIN_URL=""
ADMIN_CREATE_ACCOUNT_URL=""
ADMIN_CHANGE_PASS_URL=""
ADMIN_RESET_PASS_URL=""
LOGOUT_ADMIN_URL=""
VIEW_ADMIN_PROFILE_URL=""

export default  {
    LOGIN_ADMIN_URL,
ADMIN_CHANGE_PASS_URL,
ADMIN_CREATE_ACCOUNT_URL,
ADMIN_RESET_PASS_URL,
LOGOUT_ADMIN_URL,
VIEW_ADMIN_PROFILE_URL}