LOG_SIGNIN_URL=""
LOG_CREATE_ACCOUNT_URL=""
LOG_UPDATE_PASS=""
UPDATE_LOG_DETAILS=""
DELETE_LOG_DETAILS=""

export default  {
    LOG_CREATE_ACCOUNT_URL,
    LOG_SIGNIN_URL,
    LOG_UPDATE_PASS,
    UPDATE_LOG_DETAILS,
    DELETE_LOG_DETAILS
}