const LOG_API_NAME="/LogApi"
const LOG_SIGNIN_URL=  LOG_API_NAME+"/LogsSignIn"
const LOG_CREATE_ACCOUNT_URL=  LOG_API_NAME+"/"
const LOG_UPDATE_PASS=     LOG_API_NAME+"/"
const UPDATE_LOG_DETAILS=  LOG_API_NAME+"/"
const DELETE_LOG_DETAILS=      LOG_API_NAME+"/"

export default  {
    LOG_CREATE_ACCOUNT_URL,
    LOG_SIGNIN_URL,
    LOG_UPDATE_PASS,
    UPDATE_LOG_DETAILS,
    DELETE_LOG_DETAILS
}