LOG_USER_API="/UserApi"
LOGIN_USER_URL= LOG_USER_API+""
USER_CREATE_ACCOUNT_URL=   LOG_USER_API+""
USER_CHANGE_PASS_URL=   LOG_USER_API+""
USER_RESET_PASS_URL=   LOG_USER_API+""
LOGOUT_USER_URL=   LOG_USER_API+""
VIEW_USER_PROFILE_URL=   LOG_USER_API+""

export default  {
    LOGIN_USER_URL,
    LOGOUT_USER_URL,
    USER_CHANGE_PASS_URL,
    USER_CREATE_ACCOUNT_URL,
    USER_RESET_PASS_URL,
    VIEW_USER_PROFILE_URL
}