LOGIN_USER_URL=""
USER_CREATE_ACCOUNT_URL=""
USER_CHANGE_PASS_URL=""
USER_RESET_PASS_URL=""
LOGOUT_USER_URL=""
VIEW_USER_PROFILE_URL=""

export default  {
    LOGIN_USER_URL,
    LOGOUT_USER_URL,
    USER_CHANGE_PASS_URL,
    USER_CREATE_ACCOUNT_URL,
    USER_RESET_PASS_URL,
    VIEW_USER_PROFILE_URL
}