const LOG_USER_API="/UserApi"
const LOGIN_USER_URL= LOG_USER_API+"/LoginUser"
const USER_CREATE_ACCOUNT_URL=   LOG_USER_API+"/CreateUser"
const USER_CHANGE_PASS_URL=   LOG_USER_API+"/UserChangePass"
const USER_RESET_PASS_URL=   LOG_USER_API+"/UserResetPass"
const LOGOUT_USER_URL=   LOG_USER_API+"/logOutUser"
const VIEW_USER_PROFILE_URL=   LOG_USER_API+"/viewUserProfile"
const MANAGE_USER_ROLE = LOG_USER_API+"/ManageUserRole"
const DELETE_USER_ACCOUNT = LOG_USER_API +"/UserDlt"
const UPDATE_USER_PROFILE = LOG_USER_API +"/updateUserProfile"
const VIEW_ALL_USERS = LOG_USER_API +"/DisplayAllUsers"

export {
    LOGIN_USER_URL,
    LOGOUT_USER_URL,
    USER_CHANGE_PASS_URL,
    USER_CREATE_ACCOUNT_URL,
    USER_RESET_PASS_URL,
    VIEW_USER_PROFILE_URL,
    MANAGE_USER_ROLE,
    DELETE_USER_ACCOUNT,
    UPDATE_USER_PROFILE,
    VIEW_ALL_USERS
}