const DATA_NOT_FOUND = 1001
const LOGIN_SUCCESSFULL =1002
const PROFILE_UPDATE_SUCCESSFULL= 1003
const CONTENT_NOT_FOUND = 1004
const ERROR_MESSAGE = 1005
const INCORECT_EMAIL_PASS = 1006
const  ACCOUNT_CREATED_SUCCESSFULLY = 1007  


module.exports = {DATA_NOT_FOUND,
LOGIN_SUCCESSFULL,
PROFILE_UPDATE_SUCCESSFULL,
CONTENT_NOT_FOUND,
ERROR_MESSAGE,
INCORECT_EMAIL_PASS,
ACCOUNT_CREATED_SUCCESSFULLY

}